In [1]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split

In [51]:
x_train = pd.read_csv('C:/Users/Tirthashree/Documents/MTech/Notes/DLA/trainBoVW.csv',header=None)
print(x_train.shape)
y_train = np.array([0]*50+[1]*50+[2]*50)
x_test = pd.read_csv('C:/Users/Tirthashree/Documents/MTech/Notes/DLA/testBoVW.csv',header=None)
print(x_test.shape)
y_test = np.array([0]*50+[1]*50+[2]*50)

(150, 32)
(150, 32)


In [59]:
clf = make_pipeline(StandardScaler(), SVC(C=0.01,gamma='scale'))
clf.fit(x_train, y_train)
print('Training data:')
y_pred_train = clf.predict(x_train)
print('accuracy:',100*accuracy_score(y_train,y_pred_train))
print('confusion matrix:\n',confusion_matrix(y_train,y_pred_train))
print('Test data')
y_pred = clf.predict(x_test)
print('accuracy:',100*accuracy_score(y_test,y_pred))
print('confusion matrix:\n',confusion_matrix(y_test,y_pred))

Training data:
accuracy: 76.66666666666667
confusion matrix:
 [[44  1  5]
 [15 29  6]
 [ 2  6 42]]
Test data
accuracy: 66.0
confusion matrix:
 [[43  2  5]
 [19 24  7]
 [10  8 32]]


In [60]:
clf1 = SVC(C=0.01,kernel = 'rbf',gamma='scale')
clf1.fit(x_train, y_train)
print('Training data:')
y_pred_train = clf1.predict(x_train)
print('accuracy:',100*accuracy_score(y_train,y_pred_train))
print('confusion matrix:\n',confusion_matrix(y_train,y_pred_train))
print('Test data')
y_pred = clf1.predict(x_test)
print('accuracy:',100*accuracy_score(y_test,y_pred))
print('confusion matrix:\n',confusion_matrix(y_test,y_pred))
clf1.fit_status_

Training data:
accuracy: 73.33333333333333
confusion matrix:
 [[44  2  4]
 [17 24  9]
 [ 5  3 42]]
Test data
accuracy: 65.33333333333333
confusion matrix:
 [[42  5  3]
 [15 20 15]
 [ 5  9 36]]


0

In [5]:
# df_train = pd.read_csv('C:/Users/Tirthashree/Documents/MTech/Notes/DLA/trainBoVW.csv',header=None)
# df_train.columns = ['f01','f02','f03','f04','f05','f06','f07','f08','f09','f10','f11','f12','f13','f14','f15','f16','f17','f18','f19','f20','f21','f22','f23','f24','f25','f26','f27','f28','f29','f30','f31','f32']
# df_train['y'] = np.array([0]*50+[1]*50+[2]*50)
# df_train = shuffle(df_train)

# df_test = pd.read_csv('C:/Users/Tirthashree/Documents/MTech/Notes/DLA/testBoVW.csv',header=None)
# df_test.columns = ['f01','f02','f03','f04','f05','f06','f07','f08','f09','f10','f11','f12','f13','f14','f15','f16','f17','f18','f19','f20','f21','f22','f23','f24','f25','f26','f27','f28','f29','f30','f31','f32']
# df_test['y'] = np.array([0]*50+[1]*50+[2]*50)
# df_test = shuffle(df_test)

In [6]:
# clf2 = SVC(kernel = 'rbf',gamma='scale')
# clf2.fit(df_train.iloc[:,0:32], df_train.iloc[:,32])
# print('Training data:')
# df_pred_train = clf2.predict(df_train.iloc[:,0:32])
# print('accuracy:',100*accuracy_score(df_train.iloc[:,32],df_pred_train))
# print('confusion matrix:\n',confusion_matrix(df_train.iloc[:,32],df_pred_train))

# print('Test data')
# df_pred = clf2.predict(df_test.iloc[:,0:32])
# print('accuracy:',100*accuracy_score(df_test.iloc[:,32],df_pred))
# print('confusion matrix:\n',confusion_matrix(df_test.iloc[:,32],df_pred))
# clf2.fit_status_

Training data:
accuracy: 87.33333333333333
confusion matrix:
 [[44  2  4]
 [ 6 39  5]
 [ 0  2 48]]
Test data
accuracy: 65.33333333333333
confusion matrix:
 [[39  5  6]
 [14 22 14]
 [ 3 10 37]]


0

In [58]:
# df = pd.concat([df_train,df_test])
# X = df.iloc[:,0:32]
# Y = df.iloc[:,32]
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.5, random_state=42)

# # print(' ')
# # clf3 = make_pipeline(StandardScaler(), SVC(gamma='scale'))
# # clf3.fit(X_train, Y_train)
# # print('Training data:')
# # Y_pred_train = clf3.predict(X_train)
# # print('accuracy:',100*accuracy_score(Y_train,Y_pred_train))
# # print('confusion matrix:\n',confusion_matrix(Y_train,Y_pred_train))
# # print('Test data')
# # Y_pred = clf3.predict(X_test)
# # print('accuracy:',100*accuracy_score(Y_test,Y_pred))
# # print('confusion matrix:\n',confusion_matrix(Y_test,Y_pred))

# print(' ')
# clf4 = make_pipeline(StandardScaler(), SVC(C=0.1,kernel = 'poly',degree=4,gamma='scale'))
# clf4.fit(X_train, Y_train)
# print('Training data:')
# Y_pred_train = clf4.predict(X_train)
# print('accuracy:',100*accuracy_score(Y_train,Y_pred_train))
# print('confusion matrix:\n',confusion_matrix(Y_train,Y_pred_train))
# print('Test data')
# Y_pred = clf4.predict(X_test)
# print('accuracy:',100*accuracy_score(Y_test,Y_pred))
# print('confusion matrix:\n',confusion_matrix(Y_test,Y_pred))
# # clf4.fit_status_

 
Training data:
accuracy: 50.66666666666667
confusion matrix:
 [[20  0 37]
 [ 0  6 37]
 [ 0  0 50]]
Test data
accuracy: 42.0
confusion matrix:
 [[ 8  2 33]
 [ 2  5 50]
 [ 0  0 50]]
